global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'integration-engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['integration-engine:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121
